export const CHANGE_INTEREST_RATE = 'CHANGE_INTEREST_RATE';
export const CHANGE_PERIOD = 'CHANGE_PERIOD';
export const CHANGE_PRESENT_VALUE = 'CHANGE_PRESENT_VALUE';
export const CHANGE_NUMBER_OF_PERIODS = 'CHANGE_NUMBER_OF_PERIODS';
